on:
  workflow_dispatch:
    inputs:
      nwn_assets:
        description: 'NWN Assets'
        required: true
        default: '8193.35'
      nasher_version:
        description: 'Nasher Version'
        required: true
        default: '0.20.0'

name: Build and Publish Image

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - id: 'auth'
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            NWN_ASSETS=${{ github.event.inputs.nwn_assets }}
            NASHER_RELEASE=${{ github.event.inputs.nasher_version }}
          tags: |
            narfell/nasher:latest
            narfell/nasher:${{ github.event.inputs.nwn_assets }}_${{ github.event.inputs.nasher_version }}
          secrets: |
            GIT_AUTH_TOKEN=${{ steps.auth.outputs.access_token }}
